
main:
	arm-linux-gnueabihf-gcc -o ControlLed ControlLed.c -Wall
	arm-linux-gnueabihf-gcc -o ControlTpg ControlTpg.c -Wall
	arm-linux-gnueabihf-gcc -o ControlVdma ControlVdma.c -Wall
	arm-linux-gnueabihf-gcc -o test test.c -Wall
	arm-linux-gnueabihf-gcc -o usrSpace_MIOgpio_PS usrSpace_MIOgpio_PS.c -Wall
	arm-linux-gnueabihf-gcc -o usrSpace_pwm_EMIOgpio_PL usrSpace_pwm_EMIOgpio_PL.c -Wall
	arm-linux-gnueabihf-gcc -o usrSpace_hcsr04_EMIOgpio usrSpace_hcsr04_EMIOgpio.c -Wall
	arm-linux-gnueabihf-gcc -o usrSpace_EMIOgpio_PL usrSpace_EMIOgpio_PL.c -Wall